from django.conf.urls import patterns, include, url
from django.contrib import admin
from main.views import *
from karatekyokushin.views import *
from karateshotokan.views import *
from tournament import settings
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'system.home', name='home'),
    # url(r'^blog/', include('blog.urls')),
    # url(r"static/(?P<path>.*)$", "django.views.static.serve", {"document_root" : settings.STATIC_TEMPLATES}),
    url(r"^media/(?P<path>.*)$", "django.views.static.serve", {"document_root" : settings.MEDIA_ROOT} ),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^$', home, name='home'),
    url(r'^karatekyokushin/', KarateKyokushinMain, name='KarateKyokushinMain'),
    url(r'^karateshotokan/', KarateShotokanMain, name='KarateShotokanMain'),
    url(r'^createTournament/', createTournament, name='createTournament'),
    url(r'^create/', 'KarateKyokushinCreate', name='KarateKyokushinCreate'),
    url(r'^createShotokan/', 'KarateShotokanCreate', name='KarateShotokanCreate'),
    url(r'^chooseShotokan/', 'KarateShotokanChoose', name='KarateShotokanChoose'),
    url(r'^createTeamShotokan/', 'KarateShotokanCreateTeam', name='KarateShotokanCreateTeam'),
    url(r'^createTeam/', createTeam, name='CreateTeam'),
    url(r'^signUp/', signUp, name='signUp'),
    url(r'^signIn/', signIn, name='signIn'),
    url(r'^logout/', logout, name='logout'),
    url(r'^updateProfile/', 'main.views.updateProfile', name='updateProfile'),
    url(r'^tournamentSho/(?P<tournament_id>\d+)/', 'tournamentSho', name='tournamentSho'),
    url(r'^kyoRandPlayers/(?P<tournament_id>\d+)/', kyoRandPlayers, name='kyoRandPlayers'),
    url(r'^kyo-category/(?P<category_id>\d+)/ (?P<minround>\d+)/', kyoCategory, name='kyoCategory'),
    url(r'^kyoEditResultsI/(?P<category_id>\d+)/ ', kyoEditResultsI, name='kyoEditResultsI'),
    url(r'^kyoEditResultsII/(?P<category_id>\d+)/ ', kyoEditResultsII, name='kyoEditResultsII'),
    url(r'^kyoPrevrounds/(?P<category_id>\d+)/ (?P<minround>\d+)/', kyoPrevrounds, name='kyoPrevrounds'),
    url(r'^kyoNextrounds/(?P<category_id>\d+)/ (?P<minround>\d+)/', kyoNextrounds, name='kyoNextrounds'),
    url(r'^kyoWinnerFightKM/(?P<fight_id>\d+)/ (?P<whose>\d+)/ (?P<minround>\d+)/', kyoWinnerFightKM, name='kyoWinnerFightKM'),
    url(r'^kyoTournamentOrganization/(?P<tournament_id>\d+)/', kyoTournamentOrganization, name='kyoTournamentOrganization'),
    url(r'^shoTournamentOrganization/(?P<tournament_id>\d+)/', shoTournamentOrganization, name='shoTournamentOrganization'),
    url(r'^team/(?P<team_id>\d+)/', team, name='team'),
    url(r'^userToAdd/(?P<user_id>\d+) (?P<team_id>\d+)/', userToAdd, name='userToAdd'),
    url(r'^addPlayers/(?P<team_id>\d+)/', addPlayers, name='addPlayers'),
    url(r'^kyoPlayerToAdd/(?P<player_id>\d+) (?P<category_id>\d+)/', kyoPlayerToAdd, name='kyoPlayerToAdd'),
    url(r'^kyoPlayerToEnter/(?P<player_id>\d+) (?P<category_id>\d+)/', kyoPlayerToEnter, name='kyoPlayerToEnter'),
    url(r'^kyoDeletePlayerFromCategory/(?P<player_id>\d+) (?P<category_id>\d+)/', kyoDeletePlayerFromCategory, name='kyoDeletePlayerFromCategory'),
    url(r'^kyoAddPlayersToCategory/(?P<category_id>\d+)/', kyoAddPlayersToCategory, name='kyoAddPlayersToCategory'),
    url(r'^kyoEnterAllPlayersToCategory/(?P<category_id>\d+)(?P<user_id>\d+)/', kyoEnterAllPlayersToCategory, name='kyoEnterAllPlayersToCategory'),
    url(r'^kyoEnterPlayersTeamCate/(?P<team_id>\d+)(?P<category_id>\d+)/', kyoEnterPlayersTeamCate, name='kyoEnterPlayersTeamCate'),
    url(r'^updateTournament/(?P<tournament_id>\d+)/', updateTournament, name='updateTournament'),
    url(r'^kyoUpdateCategory/(?P<category_id>\d+)/', kyoUpdateCategory, name='kyoUpdateCategory'),
    url(r'^createCategoryKyo/(?P<tournament_id>\d+)/', createCategoryKyo, name='createCategoryKyo'),
    url(r'^kyoEnterPlayerForCategory/(?P<category_id>\d+)/ /(?P<user_id>\d+)/', kyoEnterPlayerForCategory, name='kyoEnterPlayerForCategory'),
    url(r'^playerToTeamAccept/(?P<player_id>\d+)/', playerToTeamAccept, name='playerToTeamAccept'),
    url(r'^playerToTournamentAccept/(?P<playerT_id>\d+)/', playerToTournamentAccept, name='playerToTournamentAccept'),
    url(r'^allPlayersTourAcceptByC/', allPlayersTourAcceptByC, name='allPlayersTourAcceptByC'),
    url(r'^allPlayersTourAcceptByM/', allPlayersTourAcceptByM, name='allPlayersTourAcceptByM'),
    url(r'^allTeamTourAcceptByM/(?P<team_id>\d+)/', allTeamTourAcceptByM, name='allTeamTourAcceptByM'),
    url(r'^user/', user, name='user'),
    url(r'^player/(?P<player_id>\d+)/', player, name='player'),
    url(r'^coach/(?P<coach_id>\d+)/', coach, name='coach'),
)